### PR TITLE
fix linking issue with latest vitasdk

### PR DESCRIPTION
**Pull request by soarqin**
See vitasdk/vita-headers#400

### CODE REVIEW

**Comment by CelesteBlue-dev** [comment]
so the order matters ?

**Comment by soarqin** [comment]
yeah, confirmed.
Or you can pick an old version vita-headers to resolve the problem

**Comment by yifanlu** [comment]
I'm against the idea of having to modify project to workaround SDK bugs introduced after the project has been stable.

**Comment by CelesteBlue-dev** [comment]
On this special case, the most stable is taihen and not vitasdk function names confusions.
So I agree, fix the vitasdk and don't touch taihen.

**Comment by soarqin** [comment]
> I'm against the idea of having to modify project to workaround SDK bugs introduced after the project has been stable.

Agree, this is just a temporary solution for latest vitasdk, before upstream fixes done from vitasdk maintainers.
Close this, hope they'd get a new naming rule to resolve conflict asap.

**Pull request closed without merging**
